GDSC SKHU Web - 전유진
GDSC-SKHU/GDSC-Web-Assignment-02 pull request #3
Opened 2022-11-08 04:59 UTC by yuj2n

## Description

> 구현 및 작업 내용을 적어주세요.

- table을 이용한 계산기 작성
- onclick 이벤트를 통해 함수를 발생시켜 계산
- 연산기호가 연속으로 나오거나 초기값으로 +나 숫자가 아닌값이 올 수 없도록 js 작성

## Important content

> 주의 깊게 봐야 하거나 말하고 싶은 점을 적어주세요.

- hover & 클릭 시 색 변화를 주어 동적인 느낌 표현
- css를 통해 숫자와 operator 구분 및 디자인 적용
- eval이 아닌 직접 함수를 작성하여 만들어보고 싶고 키보드를 이용한 입력 기능 추가 희망
- table 방식이 아닌 div 태그를 중복 작성 또는 button태그를 통해 만드는 방식도 만들어보고 싶음.

## Reference

> 참고한 레퍼런스가 있다면 기록해주세요.
- https://blog.cordelia273.space/32
- 아직은 자바스크립트와 구조 작성에 대해서 많이 미숙하여 구글링에 많이 의존하지만
  후에 직접 획기적인 코드를 작성할 수 있으면 좋겠음.

2022-11-08 06:39 UTC, hyesungoh approved these changes
👍 👍 👍 

고생하셨어요 👍 

은지님의 과제와 비슷한 부분이 많아, 은지님의 PR 또한 확인해 주시길 부탁드려요 !

https://github.com/GDSC-SKHU/GDSC-Web-Assignment-02/pull/1

2022-11-08 06:39 UTC, hyesungoh commented on assignment.js
> +    if(isNaN(char)==true) {
```suggestion
    if(Number.isNaN(char)==true) {
```

isNaN의 경우 아래 링크에서 `Number.isNaN`으로 바꾸는 것을 권장하고 있어요!

확인해 보시면 좋을 듯 합니다 ~
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/isNaN

2022-11-08 06:39 UTC, hyesungoh commented on assignment.js
> +        document.getElementById('display').value += char;
이렇게 if depth가 깊어진다면 clean code에서 흔히 말하곤 하는 early return 을 생각해 보시는 것을 추천드려요

https://jheloper.github.io/2019/06/write-early-return-code/

2022-11-09 05:52 UTC, hyesungoh requested changes
유진님 `./전유진/assignment.css` 처럼 폴더 안에 넣어주셔야 돼요~

2022-11-09 05:53 UTC, hyesungoh commented
이렇게 PR을 올린 후에 변화가 있을 때는, 다시 브랜치를 만드는 게 아니라

PR을 올린 브랜치에 다시 커밋하면 변경 사항이 적용 됩니다 ! @yuj2n

2022-11-09 12:22 UTC, yuj2n commented on assignment.js
> +    if(isNaN(char)==true) {
확인했습니다!! number.을 붙여주지 않으면 인자를 강제로 Number로 변환하는군요,,

2022-11-09 12:25 UTC, yuj2n commented on assignment.js
> +        document.getElementById('display').value += char;
감사합니다. 한 번 시도해볼게요!

2022-11-09 12:38 UTC, hyesungoh requested changes
![스크린샷 2022-11-09 오후 9 38 09](https://user-images.githubusercontent.com/26461307/200832352-677b5f99-956c-4885-9c19-bbf841c45c81.png)

기존에 루트에 있는 파일들 지워주세요 ~

2022-11-09 12:39 UTC, hyesungoh approved these changes

2022-11-09 13:28 UTC, NohWookJin approved these changes
죄송해용 제가 2000원 내겠습니당 ㅋㅋㅋㅋㅋ

2022-11-09 13:28 UTC, NohWookJin commented on assignment.css
> +}
hover와 active를 사용하셨군요! 멋있습니당 👍 👍 👍

2022-11-09 13:49 UTC, merged