GDSC SKHU Web - 이예슬
GDSC-SKHU/GDSC-Web-Assignment-02 pull request #9
Opened 2022-11-09 04:34 UTC by yeaseul7

계산기 과제

## Description

> 구현 및 작업 내용을 적어주세요.

- 버튼별로 함수 만들어서 클릭했을때 작동하도록 구현
- 나만의 스타일로 css 작업
- 버튼 클릭했을때 result 클래스에 다 추가하고 eval 써서 한번에 계산

## Important content

> 주의 깊게 봐야 하거나 말하고 싶은 점을 적어주세요.

- 버튼별로 하나하나 함수를 만들고 queryselector을 썼는데 이게 맞는건지 잘 모르겠다는 점
- 구현은 했는데 코드가 복잡하고 양이 많음
- 줄일 수 있는 부분을 줄이는 수정을 하고싶다고 생각

## Reference

> 참고한 레퍼런스가 있다면 기록해주세요.
movie 만들었던 js 파일

2022-11-09 05:54 UTC, hyesungoh requested changes
예슬님 ~ `이예슬/index.html`

이렇게 depth가 한 번 더 안들어가게 수정해주세요 ~

2022-11-09 05:54 UTC, hyesungoh commented
이렇게 PR을 올린 후에 변화가 있을 때는, 다시 브랜치를 만드는 게 아니라

PR을 올린 브랜치에 다시 커밋하면 변경 사항이 적용 됩니다 ! @yeaseul7

2022-11-09 07:53 UTC, zoeyourlife commented
전반적인 계산기 디자인이 아기아기한 느낌입니다 !

2022-11-09 07:55 UTC, hyesungoh commented
> 전반적인 계산기 디자인이 아기아기한 느낌입니다 !

재훈님 요거는 코멘트입니다 ~ 리뷰로 남겨주세요 ~

2022-11-09 07:56 UTC, zoeyourlife commented on 이예슬/study2/index.js
> +    numberButton9.addEventListener("click", writeNumber9);
궁금한 점이 있습니다 ! 이렇게 따로따로 설정하신 이유가 있으신가요?

2022-11-09 07:56 UTC, zoeyourlife commented on 이예슬/study2/index.css
> +    padding: 9px;
👍 👍

2022-11-09 10:05 UTC, yeaseul7 commented on 이예슬/study2/index.js
> +    numberButton9.addEventListener("click", writeNumber9);
아니요 방법을 생각못해서 따로 따로 설정했어요!

2022-11-09 11:47 UTC, hyesungoh approved these changes
고생하셨습니다 👍 👍 👍 

여기서 반복을 줄일 수 있는 방법에 대해 고민해 보셨으면 좋겠어요

가장 간단히는 숫자들에 같은 `js-number` 같은 클래스를 준 후, `event.target.value`를 통해 계산식에 포함하는 방법이 있을 거 같구요.

물론 다른 분들이 하신 방법을 확인해 보는 것도 좋구요 ~ 👍 👍

2022-11-09 11:47 UTC, hyesungoh commented on 이예슬/index.js
> +const numberButton9 = document.querySelector(".js-number9");
ㅋㅋㅋㅋㅋㅋㅋㅋ 고생하셨습니다 👍 👍 👍

2022-11-09 12:37 UTC, merged

2022-11-12 09:15 UTC, yeaseul7 commented on 이예슬/index.js
> +const numberButton9 = document.querySelector(".js-number9");
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 감사합니다.....ㅠ..ㅠ